using System.Drawing;
using Mandelbrot.ExtensionMethods;
using Mandelbrot.Helpers.ColorKernels;
using Mandelbrot.Helpers.ColorKernels.Implementations;
using Mandelbrot.Helpers.ColorKernels.Implementations.DoubleKernels;
using Mandelbrot.Model;

namespace Mandelbrot.Generators;

/// <summary>
///     Class that is used to turn raw Mandelbrot data into color images.
/// </summary>
public class ColorPicker
{
    private readonly Color[] _colorPalette;
    private readonly double _colorSkew;
    private readonly double _ditherRatio;
    private static readonly string pallettesFolder = "Storage/Pallettes/";


    /// <summary>
    ///     Initializes a new instance of the
    ///     <see cref="ColorPicker"/> class.
    /// </summary>
    /// <param name="palletteName">
    ///     The name of the pallette file.
    ///     The file should be x by 1 in size.
    /// </param>
    /// <param name="colorSkew">
    ///     Variable that determines the relative sizes of colors in the palette.
    ///     <para>
    ///     A value of 1 means all colors are represented equally.
    ///     A value of x means that the color corresponding to the data with the
    ///     highest escape speed is present x times as much as the average color.
    ///     All other colors are scaled linearly.
    ///     </para>
    ///     Value should be in range (0, 1].
    /// </param>
    /// <param name="ditherRatio">
    ///     Variable that determines the relative size that is affected by dithering.
    ///     <para>Only used in <see cref="GetDitheredColor"/>.</para>
    /// </param>
    /// <remarks>
    ///     colorSkew and ditherRatio are a temporary implementation of functionality
    ///     that will be held in the ColorPalette class in future.
    /// </remarks>
    public ColorPicker(string palletteName, double colorSkew = 1d, double ditherRatio = 0.2d)
    {
        _colorSkew = colorSkew;
        _ditherRatio = ditherRatio;

        var path = Path.Combine(
            pallettesFolder,
            palletteName);

        if (!File.Exists(path))
        {
            throw new FileNotFoundException($"Couldn't find this pallette: {path}");
        }

        var pallette = new Bitmap(path);
        var colorList = new List<Color> ();

        for (int i = 0; i < pallette.Width; i++)
        {
            var color = pallette.GetPixel(i, 0);
            colorList.Add(color);
        }

        _colorPalette = colorList.ToArray();
    }

    /// <summary>
    ///     Generate an image with color bands.
    /// </summary>
    /// <param name="iterData">
    ///     The data generated by the <see cref="Calculator"/> class.
    /// </param>
    /// <returns>
    ///     A mandelbrot image with bounded colors, including meta data.
    /// </returns>
    public BrotImage GetBandedColor(IterationData iterData)
    {
        var kernel = new BandedKernel(iterData, _colorPalette);

        var result = ImageLooper(kernel);
        var image = result.Item1;
        var colorTime = result.Item2;

        return iterData.ToBrotImage(image, colorTime);
    }

    /// <summary>
    ///     Generate an image with continuous coloring.
    /// </summary>
    /// <param name="iterData">
    ///     The raw data generated by the <see cref="Calculator"/> class.
    ///     Needs to have escape speeds in addition to iterations data.
    /// </param>
    /// <returns>
    ///     A mandelbrot image with continuous coloring, including meta data.
    /// </returns>
    public BrotImage GetContinuousColor(IterationData iterData)
    {
        var kernel = new ContinuousKernel(iterData, _colorPalette, _colorSkew);

        var result = ImageLooper(kernel);
        var image = result.Item1;
        var colorTime = result.Item2;

        return iterData.ToBrotImage(image, colorTime);
    }

    /// <summary>
    ///     Generates an image with dithering inbetween different colors.
    /// </summary>
    /// <param name="iterData">
    ///     The raw data returned by the <see cref="Calculator"/> class.
    ///     Needs to have escape speeds in addition to iterations data.
    /// </param>
    /// <returns></returns>
    /// <remarks>
    ///     Best used for pixel art.
    /// </remarks>
    public BrotImage GetDitheredColor(IterationData iterData)
    {
        var kernel = new DitheredKernel(iterData, _colorPalette, _colorSkew, _ditherRatio);

        var result = ImageLooper(kernel);
        var image = result.Item1;
        var colorTime = result.Item2;

        return iterData.ToBrotImage(image, colorTime);
    }

    private static (Bitmap, TimeSpan) ImageLooper(IColorKernel kernel)
    {
        var startTime = DateTime.Now;
        var sizes = kernel.GetImageSize();
        var xSize = sizes.Item1;
        var ySize = sizes.Item2;
        var image = new Bitmap(xSize, ySize);

        for (int x = 0; x < xSize; x++)
        for (int y = 0; y < ySize; y++)
        {
            image.SetPixel(x, y, kernel.Apply(x, y));
        }

        var colorTime = DateTime.Now - startTime;
        return (image, colorTime);
    }
}